module(load="imtcp")

template(
  name="KTXRemoteFile"
  type="string"
  string="/srv/ktx/logs/remote/%HOSTNAME:::secpath-replace%/%PROGRAMNAME:::secpath-replace%.log"
)

ruleset(name="KTXRemote") {
  action(
    type="omfile"
    dynaFile="KTXRemoteFile"
    createDirs="on"
    dirCreateMode="0750"
    fileCreateMode="0640"
  )
  stop
}

input(type="imtcp" port="514" ruleset="KTXRemote")
