Port 2222
HostKey /etc/ssh/ktx-hostkeys/ssh_host_ed25519_key
PermitRootLogin no
PasswordAuthentication no
KbdInteractiveAuthentication no
PubkeyAuthentication yes
X11Forwarding no
AllowUsers site
AuthorizedKeysFile .ssh/authorized_keys
