[supervisord]
nodaemon=true
logfile=/dev/null

[program:hbbs]
command=/usr/local/bin/hbbs -r %(ENV_RUSTDESK_RELAY_HOST)s:21117
directory=/data
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:hbbr]
command=/usr/local/bin/hbbr
directory=/data
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
